title: Nakul Vankadari Ramesh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  4+ years of experience in IT industry as a Systems Programmer and Software Developer. 
  Currently pursuing Master of Science in Computer Science at Northeastern University.
  <br><br>
  Seeking Full-time opportunities in Software Development starting Jan'20. Achieved Research Fellowship at Northeastern University. 
  <br><br>
  <a href="https://www.linkedin.com/in/nakulvr/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
